// <auto-generated />
using JamesTranproject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JamesTranproject.Migrations
{
    [DbContext(typeof(ReactContext))]
    partial class ReactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JamesTranproject.Models.Anouncement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DateTimeUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Anouncements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTimeUse = "05/Jan/2021",
                            Img = "Image.image_gallery",
                            Introduction = "New Wellness Lorem ipsum dolor sit amet, consetetur sadipscing elitrinvidunt ut labore et dolore aaliquya erat, sed diam voluptuaaa vero eos et accusam et justo duo d ea rebum.",
                            ResourceUse = "Human Resource",
                            Title = "New Learing System Is Live"
                        },
                        new
                        {
                            Id = 2,
                            DateTimeUse = "05/Jan/2021",
                            Img = "Image.image_gallery_1",
                            Introduction = "New Wellness Lorem ipsum dolor sit amet, consetetur sadipscing elitrinvidunt ut labore et dolore aaliquya erat, sed diam voluptuaaa vero eos et accusam et justo duo d ea rebum.",
                            ResourceUse = "Human Resource",
                            Title = "New Learing System Is Live"
                        },
                        new
                        {
                            Id = 3,
                            DateTimeUse = "05/Jan/2021",
                            Img = "Image.image_gallery_2",
                            Introduction = "New Wellness Lorem ipsum dolor sit amet, consetetur sadipscing elitrinvidunt ut labore et dolore aaliquya erat, sed diam voluptuaaa vero eos et accusam et justo duo d ea rebum.",
                            ResourceUse = "Human Resource",
                            Title = "New Learing System Is Live"
                        },
                        new
                        {
                            Id = 4,
                            DateTimeUse = "05/Jan/2021",
                            Img = "Image.image_gallery_3",
                            Introduction = "New Wellness Lorem ipsum dolor sit amet, consetetur sadipscing elitrinvidunt ut labore et dolore aaliquya erat, sed diam voluptuaaa vero eos et accusam et justo duo d ea rebum.",
                            ResourceUse = "Human Resource",
                            Title = "New Learing System Is Live"
                        });
                });

            modelBuilder.Entity("JamesTranproject.Models.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day = "Jan",
                            Img = "Image.clock",
                            Number = "01",
                            Time = "09:00 AM - 09:30 AM",
                            Title = "Register Portal"
                        },
                        new
                        {
                            Id = 2,
                            Day = "Jan",
                            Img = "Image.clock",
                            Number = "02",
                            Time = "09:00 AM - 09:30 AM",
                            Title = "Register Portal"
                        },
                        new
                        {
                            Id = 3,
                            Day = "Jan",
                            Img = "Image.clock",
                            Number = "03",
                            Time = "09:00 AM - 09:30 AM",
                            Title = "Register Portal"
                        },
                        new
                        {
                            Id = 4,
                            Day = "Jan",
                            Img = "Image.clock",
                            Number = "04",
                            Time = "09:00 AM - 09:30 AM",
                            Title = "Register Portal"
                        });
                });

            modelBuilder.Entity("JamesTranproject.Models.HowDoI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HowDoIs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiut aliquip ex ea commodo consequat. Duis uis.",
                            IconAnswer = "Image.expand",
                            IconQuestion = "Image.collapse",
                            Question = "What do you do?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiut aliquip ex ea commodo consequat. Duis uis.",
                            IconAnswer = "Image.expand",
                            IconQuestion = "Image.collapse",
                            Question = "What do you do?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiut aliquip ex ea commodo consequat. Duis uis.",
                            IconAnswer = "Image.expand",
                            IconQuestion = "Image.collapse",
                            Question = "What do you do?"
                        });
                });

            modelBuilder.Entity("JamesTranproject.Models.ImageGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImageGallerys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Img = "Image.image_gallery_1"
                        },
                        new
                        {
                            Id = 2,
                            Img = "Image.image_gallery_2"
                        },
                        new
                        {
                            Id = 3,
                            Img = "Image.image_gallery_3"
                        },
                        new
                        {
                            Id = 4,
                            Img = "Image.image_gallery_4"
                        });
                });

            modelBuilder.Entity("JamesTranproject.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DateTimeUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTimeUse = "05/Jan/2021",
                            Img = "Image.markgroup2",
                            Introduction = "New Wellness Lorem ipsum dolor sit amet, consetetur sadipscing elitrinvidunt ut labore et dolore aaliquya erat, sed diam voluptuaaa vero eos et accusam et justo duo d ea rebum.",
                            Title = "Tomorrow Healthy Check"
                        },
                        new
                        {
                            Id = 2,
                            DateTimeUse = "05/Jan/2021",
                            Img = "Image.markgroup_1",
                            Introduction = "New Wellness Lorem ipsum dolor sit amet, consetetur sadipscing elitrinvidunt ut labore et dolore aaliquya erat, sed diam voluptuaaa vero eos et accusam et justo duo d ea rebum.",
                            Title = "Tomorrow Healthy Check"
                        },
                        new
                        {
                            Id = 3,
                            DateTimeUse = "05/Jan/2021",
                            Img = "Image.markgroup_2",
                            Introduction = "New Wellness Lorem ipsum dolor sit amet, consetetur sadipscing elitrinvidunt ut labore et dolore aaliquya erat, sed diam voluptuaaa vero eos et accusam et justo duo d ea rebum.",
                            Title = "Tomorrow Healthy Check"
                        },
                        new
                        {
                            Id = 4,
                            DateTimeUse = "05/Jan/2021",
                            Img = "Image.markgroup_3",
                            Introduction = "New Wellness Lorem ipsum dolor sit amet, consetetur sadipscing elitrinvidunt ut labore et dolore aaliquya erat, sed diam voluptuaaa vero eos et accusam et justo duo d ea rebum.",
                            Title = "Tomorrow Healthy Check"
                        });
                });

            modelBuilder.Entity("JamesTranproject.Models.QuickLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuickLinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Img = "Image.icon",
                            Title = "Training"
                        },
                        new
                        {
                            Id = 2,
                            Img = "Image.icon_1",
                            Title = "Organization"
                        },
                        new
                        {
                            Id = 3,
                            Img = "Image.icon_2",
                            Title = "Task"
                        });
                });

            modelBuilder.Entity("JamesTranproject.Models.VideoGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGallerys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Video = "Image.video"
                        },
                        new
                        {
                            Id = 2,
                            Video = "Image.video_1"
                        },
                        new
                        {
                            Id = 3,
                            Video = "Image.video_2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
